### ISSUE TITLE
Extra JSON data traceback

### ISSUE THREAD

**Issue by grahame** [grahame/wrfy#1]
progress bar code exploding occasionally, code was cargo-culted from docker-py:

```
Traceback (most recent call last):
  File "/usr/local/bin/wrfy", line 9, in <module>
    load_entry_point('wrfy', 'console_scripts', 'wrfy')()
  File "/Users/grahame/code/wrfy/wrfy/cli.py", line 182, in main
    args.func(args)
  File "/Users/grahame/code/wrfy/wrfy/cli.py", line 34, in pull_all
    cli.pull(tag, stream=True))
  File "/Users/grahame/code/wrfy/wrfy/util.py", line 58, in print_status_stream
    status = json.loads(line.decode('utf8'))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
```

**Comment by grahame** [comment]
This seems to have been sorted out in docker itself.
