### ISSUE TITLE
pull-all breaks on local only images

### ISSUE THREAD

**Issue by aahunter** [grahame/wrfy#9]
```
› wrfy pull-all                        
 - pulling tag: aaaasomerandomimage:latest
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/docker/client.py", line 150, in _raise_for_status
    response.raise_for_status()
  File "/env/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.22/images/create?fromImage=aaaasomerandomimage&tag=latest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/bin/wrfy", line 9, in <module>
    load_entry_point('wrfy', 'console_scripts', 'wrfy')()
  File "/app/wrfy/cli.py", line 265, in main
    args.func(args)
  File "/app/wrfy/cli.py", line 41, in pull_all
    pull_tags(tags)
  File "/app/wrfy/cli.py", line 36, in pull_tags
    cli.pull(tag, stream=True))
  File "/env/lib/python3.5/site-packages/docker/api/image.py", line 200, in pull
    self._raise_for_status(response)
  File "/env/lib/python3.5/site-packages/docker/client.py", line 153, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'repository aaaasomerandomimage not found: does not exist or no pull access'")
```

**Comment by grahame** [comment]
Resolved by a patch from @aahunter :-)
